// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tourist_Project_MVC.Data;

#nullable disable

namespace Tourist_Project_MVC.Migrations
{
    [DbContext(typeof(TouristContext))]
    [Migration("20260629121454_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tourist_Project_MVC.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Lat")
                        .HasColumnType("real");

                    b.Property<float>("Long")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OpeningHours")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TicketPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Paris",
                            Lat = 48.8584f,
                            Long = 2.2945f,
                            Name = "Eiffel Tower",
                            description = "Iconic iron tower."
                        },
                        new
                        {
                            Id = 2,
                            City = "Rome",
                            Lat = 41.8902f,
                            Long = 12.4922f,
                            Name = "Colosseum",
                            description = "Ancient Roman amphitheater."
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("MissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsReward")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Take a photo at the top of the Eiffel Tower",
                            DestinationId = 1,
                            MissionType = "Photography",
                            PointsReward = 100,
                            Title = "Parisian Explorer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Visit the underground chambers of the Colosseum",
                            DestinationId = 2,
                            MissionType = "Exploration",
                            PointsReward = 120,
                            Title = "Gladiator Walk"
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Redemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsRedeemed")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedemptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RewardId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TouristId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.HasIndex("TouristId");

                    b.ToTable("Redemptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ECO10-XYZ",
                            PointsRedeemed = 100,
                            RedemptionDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RewardId = 1,
                            Status = "Active",
                            TouristId = 1
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointsRequired")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Get 10% off your next stay at EcoStay",
                            ExpirationDate = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PointsRequired = 100,
                            QuantityAvailable = 50,
                            RewardType = "Discount",
                            SponsorId = 2,
                            Title = "10% Hotel Discount"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Complimentary walking tour by Global Travel Co.",
                            ExpirationDate = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PointsRequired = 80,
                            QuantityAvailable = 20,
                            RewardType = "Experience",
                            SponsorId = 1,
                            Title = "Free City Tour"
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, London",
                            ContactNumber = 5550192,
                            Name = "Global Travel Co.",
                            Type = "Agency"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Green Rd, Berlin",
                            ContactNumber = 5550143,
                            Name = "EcoStay Hotels",
                            Type = "Hospitality"
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Tourist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("point_Balance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tourists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            IdNumber = "US123456",
                            Name = "John Doe",
                            Nationality = "American",
                            Passport = "P987654",
                            Password = "HashedPassword123",
                            RegisterDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point_Balance = 150
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            IdNumber = "UK789101",
                            Name = "Jane Smith",
                            Nationality = "British",
                            Passport = "P112233",
                            Password = "HashedPassword456",
                            RegisterDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point_Balance = 50
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.TripDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("TripPlanId")
                        .HasColumnType("int");

                    b.Property<int>("Visit_Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TripPlanId");

                    b.ToTable("TripDestinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 1,
                            TripPlanId = 1,
                            Visit_Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalDate = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureDate = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 2,
                            TripPlanId = 1,
                            Visit_Order = 2
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.TripPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TouristId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TouristId");

                    b.ToTable("TripPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Summer Europe Trip",
                            TouristId = 1
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.UserMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Completed_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TouristId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("TouristId");

                    b.ToTable("UserMissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed_At = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MissionId = 1,
                            PointsEarned = 100,
                            Status = "Completed",
                            TouristId = 1
                        },
                        new
                        {
                            Id = 2,
                            Completed_At = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MissionId = 2,
                            PointsEarned = 0,
                            Status = "In Progress",
                            TouristId = 2
                        });
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Mission", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Destination", "Destination")
                        .WithMany("Missions")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Redemption", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Reward", "Reward")
                        .WithMany("Redemptions")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourist_Project_MVC.Models.Tourist", "Tourist")
                        .WithMany("Redemptions")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Reward", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Sponsor", "Sponsor")
                        .WithMany("Rewards")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.TripDestination", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Destination", "Destination")
                        .WithMany("TripDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourist_Project_MVC.Models.TripPlan", "TripPlan")
                        .WithMany("TripDestinations")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.TripPlan", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Tourist", "Tourist")
                        .WithMany("TripPlans")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.UserMission", b =>
                {
                    b.HasOne("Tourist_Project_MVC.Models.Mission", "Mission")
                        .WithMany("UserMissions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourist_Project_MVC.Models.Tourist", "Tourist")
                        .WithMany("UserMissions")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Destination", b =>
                {
                    b.Navigation("Missions");

                    b.Navigation("TripDestinations");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Mission", b =>
                {
                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Reward", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Sponsor", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.Tourist", b =>
                {
                    b.Navigation("Redemptions");

                    b.Navigation("TripPlans");

                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("Tourist_Project_MVC.Models.TripPlan", b =>
                {
                    b.Navigation("TripDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
